-- 1)
    SELECT FLOOR(15.7)"Floor" FROM DUAL;

-- 2)
    SELECT CHR(68) || CHR(79) || CHR(71) "Dog" FROM DUAL;

-- 3)
    SELECT ASCII('Q') FROM DUAL;

-- 4) 
    SELECT CONCAT( CONCAT ( ename, ' Is a '),job)"Job" FROM EMP WHERE EMPNO = 7900; 

-- 5)
    SELECT COUNT(*)"Total" FROM EMP; 

-- 6)
    SELECT COUNT(DISTINCT JOB) "JOBS" FROM EMP;

-- 7)
    SELECT CURRENT_DATE FROM DUAL;

-- 8)
    -- Error : ORA-00904: "CURRENT_TIME": invalid identifier
    --  Ans : SELECT CURRENT_TIMESTAMP FROM DUAL;
    SELECT CURRENT_TIME FROM DUAL;
    

-- 9)
    -- Error : ORA-00904: "DATABASE": invalid identifier
    SELECT DATABASE() FROM DUAL;

-- 10)
    SELECT DECODE (DEPTNO,10,'ACCOUNTING',20,'RESEARCH',30,'SALES',40,'OPERATIONS','NONE') FROM DEPT;

-- 11)
    SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;

-- 12)
    SELECT GREATEST('HARRY','HARRIOT','HAROLD') "LEAST" FROM DUAL;

-- 13)
    SELECT LEAST('HARRY','HARRIOT','HAROLD') "LEAST" FROM DUAL;

-- 14)
    -- Error : ORA-00904: "HOUR": invalid identifier
    SELECT HOUR('14:03:01') FROM DUAL;

-- 15)
    -- Error : ORA-00904: "NOW": invalid identifier
    SELECT NOW() FROM DUAL;

-- 16)
    -- Error : ORA-00904: "MONTHNAME": invalid identifier
    SELECT MONTHNAME(CURRENTDATE()) FROM DUAL;

-- 17)
    SELECT MONTHS_BETWEEN(TO_DATE('02-02-1995','MM-DD-YYYY'), TO_DATE('01-01-1995','MM-DD-YYYY')) "Months" FROM DUAL;

-- 18)
    SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 19)
    SELECT NEXT_DAY('15-MAR-92','TUESDAY') "NEXT DAY" FROM DUAL;

-- 20)
    SELECT ENAME,NVL(TO_CHAR(COMM),'NOT APPLICABLE') "COMMISSION" FROM EMP WHERE DEPTNO=30;

-- 21)
    SELECT SAL + NVL(COMM,0) FROM EMP;

-- 22)
    SELECT REPLACE('JACK AND JUE','J','BL') "CHANGES" FROM DUAL;

-- 23)
    SELECT ROUND(TO_DATE('27-OCT-92'), 'YEAR') "FIRST OF THE YEAR" FROM DUAL;

-- 24)
    SELECT ROUND(54.399,2) FROM DUAL;

-- 25)
    SELECT RPAD('ENAME',12,'AB') "RPAD EXAMPLE" FROM EMP WHERE ENAME='TURNER';

-- 26)
    SELECT RTRIM('TURNERyxXxy','xy') "RTRIM EXAMPLE" FROM DUAL;

-- 27)
    SELECT SUBSTR('ABCDEFG',3,4) "Subs" FROM DUAL;

-- 28)
    SELECT SUBSTRB('ABCDEFG',5,4) "Substring With Bytes" FROM DUAL;

-- 29)
    SELECT DEPTNO, SUM(SAL) TOTALSALARY FROM EMP GROUP BY DEPTNO;

-- 30)
    SELECT MAX(SAL) FROM EMP;

-- 31)
    SELECT MIN(SAL), MAX(SAL) FROM EMP;

-- 32)
    SELECT TO_CHAR(SYSDATE,'Day,Month,DD,YYYY')"TO_CHAR Example" FROM DUAL;

-- 33)
    SELECT TO_CHAR(SYSDATE,'DDSP, YYYYSP')"TO_CHAR Example" FROM DUAL;

-- 34) Reapeat Command No.32

-- 35)
    SELECT TO_CHAR(SYSDATE,'DDSP MM YYYYSP HH')"TO_CHAR Example" FROM DUAL;

-- 36)
    SELECT TO_CHAR(SYSDATE,'ddSP MM yyyySP HH')"TO_CHAR Example" FROM DUAL;

-- 37)
    SELECT TO_CHAR(SYSDATE,'DDSP MM YYYYSP HHSP')"TO_CHAR Example" FROM DUAL;

-- 38)
    SELECT TO_CHAR(SYSDATE,'DDSP MM YYYYSP HHSP miSP')"TO_CHAR Example" FROM DUAL;

-- 39)
    SELECT TO_CHAR(SYSDATE,'DDSP MM YYYYSP HHSP MISP')"TO_CHAR Example" FROM DUAL;

-- 40)
    -- Error: ORA-01821: date format not recognized
    SELECT TO_DATE('JANUARY 26, 1996, 12:38 A.M','Month dd YYYY HH:MI A.M') FROM DUAL;
    
    -- SELECT TO_DATE('JANUARY 26, 1996, 12:38 A.M','MM DD, YYYY, HH:MI A.M') FROM DUAL;

-- 41)
    UPDATE EMP SET SAL = SAL + TO_NUMBER('100.52','9999.99') WHERE ENAME='BLAKE';

-- 42)
    SELECT TRANSLATE('2KRW229','0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ','9999999999XXXXXXXXXXXXXXXXXXXXXXXXXX')"Licence" FROM DUAL;  

-- 43)
    SELECT TRIM('O' FROM 'OLDMAN') FROM DUAL;

-- 44)
    SELECT INITCAP('the soap')"Capitals" FROM DUAL;

-- 45)
    SELECT UPPER('lower') FROM DUAL;

-- 46)
    SELECT LOWER('LOWER') FROM DUAL;

-- 47)
    SELECT INSTR('CORPORATE FLOOR','OR',3,2) "Instring" FROM DUAL;

-- 48)
    SELECT LENGTH('CANDIDE') "Length in Characters" FROM DUAL;

-- 49)
    SELECT LPAD('Page1',15,'*') "LPAD Example" FROM DUAL;