-- (1) Create Above Tables 

    CREATE TABLE ACMASTER -- Parent Table
    (
        ACNO NUMBER(3) CONSTRAINT PY_KEY PRIMARY KEY,
        NAME VARCHAR2(10),
        ADATE DATE,
        BAL NUMBER(9,2)
    );

    CREATE TABLE ACTRAN -- Child Table
    (
        TNO NUMBER(3),
        TDATE DATE,
        AMOUNT NUMBER(7,2),
        TYPE CHAR(1),
        ACNO NUMBER(3) CONSTRAINT FG_KEY REFERENCES ACMASTER
    );

-- (2) Insert 10 records in ACMASTER table
    INSERT INTO ACMASTER VALUES(101,'Ashok','1-APR-1997',5000);
    INSERT INTO ACMASTER VALUES(102,'Nilesh','2-JUN-1998',1000);
    INSERT INTO ACMASTER VALUES(103,'RITESH','4-JUL-1998',2060);
    INSERT INTO ACMASTER VALUES(104,'MUKESH','20-DEC-1998',5000);
    INSERT INTO ACMASTER VALUES(105,'JAYESH','25-DEC-1998 ',60000);
    INSERT INTO ACMASTER VALUES(106,'RAJESH','26-JAN-1999',2400);
    INSERT INTO ACMASTER VALUES(107,'KUNAL','21-JAN-1999',1500);
    INSERT INTO ACMASTER VALUES(108,'DEVANG','20-JAN-1999',1999);
    INSERT INTO ACMASTER VALUES(109,'ABHAY','26-FEB-1999',2050);
    INSERT INTO ACMASTER VALUES(110,'KAPIL','25-MAR-1999',1000);

-- Geting Data From The Parent Table
    SELECT * FROM ACMASTER;

-- View The Parent Table Structure
    DESCRIBE  ACMASTER;

-- Geting Data Into The Child Table 
    SELECT * FROM ACTRAN;

-- View The Child Table Structure
    DESCRIBE ACTRAN;

-- Drop Child Table
    DROP TABLE ACTRAN;

-- Drop Parent Table
    DROP TABLE ACMASTER;

-- (3) Insert 10 records in ACTRAN table
    INSERT INTO ACTRAN VALUES(1,'1-APR-2000',500,'W',101);
    INSERT INTO ACTRAN VALUES(2,'2-JUN-2000',1000,'D',101);
    INSERT INTO ACTRAN VALUES(3,'4-JUL-2000 ',500,'W',102);
    INSERT INTO ACTRAN VALUES(4,'20-DEC-2000',6000,'D',103);
    INSERT INTO ACTRAN VALUES(5,'25-DEC-2001 ',200,'D',105);
    INSERT INTO ACTRAN VALUES(6,'26-JAN-2001 ',1500,'D',106);
    INSERT INTO ACTRAN VALUES(7,'21-JAN-2001',3000,'D',105);
    INSERT INTO ACTRAN VALUES(8,'20-JAN-2002',5000,'D',102);
    INSERT INTO ACTRAN VALUES(9,'26-FEB-2002',50000,'D',101);
    INSERT INTO ACTRAN VALUES(10,'25-MAR-2003',4500,'D',109);

--(4) Add column USERNM VARCHER2(10) in ACTRAN table
    ALTER TABLE ACTRAN ADD (USERNM VARCHAR(10));

--(5) Add Constraint UNIQUE In TNO Column.
    ALTER TABLE ACTRAN ADD CONSTRAINT TNO UNIQUE(TNO);

--(6) Remove Constraints Primary Key From ACMASTER Table

    -- Error :- ORA-02273: This Unique/Primary Key Is Referenced By Some Foreign Keys

    -- Firest Remove The Foreign Key
        ALTER TABLE ACTRAN DROP CONSTRAINT FG_KEY;
    
    -- Now Try To Remove PRIMARY KEY
        ALTER TABLE ACMASTER DROP CONSTRAINT PY_KEY;

--(7) Decrease The Size VARCHAR2(8) Of NAME Column In ACMASTER Table
    ALTER TABLE ACMASTER MODIFY NAME VARCHAR(8);

--(8) Remove Foreign Key Constraint From ACTRAN Table.
    ALTER TABLE ACTRAN DROP CONSTRAINT FG_KEY;

--(9) Add Constraints Primary Key In ACMASTER Table.
    ALTER TABLE ACMASTER ADD CONSTRAINT ACNO PRIMARY KEY(ACNO);

--(10) Add Constraints NOT NULL In NAME Column In ACMASTER Table.
    ALTER TABLE ACMASTER MODIFY NAME NOT NULL;

-- (11) Add Constraints CHECK(BAL>0) in ACMASTER Table. 
    ALTER TABLE ACMASTER ADD CONSTRAINT CHECL1 CHECK(BAL>0);

-- (12) Rename Any One Column In Any Table (Check Is It Possible). 
	ALTER TABLE ACMASTER RENAME COLUMN NAME TO NAME1;

--(13) Remove NOT NULL Constraint Of NAME Column From ACMASTER Table.
    ALTER TABLE ACMASTER MODIFY NAME NULL;
   
    --ALTER TABLE ACMASTER MODIFY NAME NULL;

--(14) Remove Check Constraints Of BAL Column From ACMASTER Table. 
    ALTER TABLE ACMASTER DROP CONSTRAINT CHECL1;

--(15) Insert USERNM ‘SCOTT’ In All Rows Of ACTRAN
    UPDATE ACTRAN SET USERNM='SCOTT';