CREATE TABLE AUTHOR
(
    AUTHORID NUMBER(3),
    SURNAME VARCHAR(20),
    AGE NUMBER (3),
    GENDER VARCHAR(7)
);

CREATE TABLE BOOK
(
    BOOKID NUMBER(3),
    TITLE VARCHAR(20),
    PRICE NUMBER(5,2)
);

INSERT INTO AUTHOR VALUES(1,'Marvel',30,'Male');
INSERT INTO AUTHOR VALUES(2,'BilGates',20,'Male');
INSERT INTO AUTHOR VALUES(3,'SuperMan',60,'Male');
INSERT INTO AUTHOR VALUES(4,'BatName',30,'Male');

INSERT INTO BOOK VALUES(1,'IronMan',300.12);

SELECT * FROM AUTHOR;
SELECT * FROM BOOK;
