CREATE TABLE STUDENT16
(
    SID NUMBER(3) NOT NULL,
    SNAME VARCHAR(23) NOT NULL,
    SROLLNO NUMBER(3) NOT NULL
);

INSERT INTO STUDENT16 VALUES(1,'Rajesh',11);
INSERT INTO STUDENT16 VALUES(2,'Mahesh',22);
INSERT INTO STUDENT16 VALUES(3,'Rakesh',31);
INSERT INTO STUDENT16 VALUES(4,'Manan',21);
INSERT INTO STUDENT16 VALUES(5,'Raman',10);
INSERT INTO STUDENT16 VALUES(6,'Kishan',21);