SET SERVEROUTPUT ON

DECLARE 
	NUM1 NUMBER(2);
	NUM2 NUMBER(2);
	SUM1 NUMBER(3);
BEGIN
	NUM1 := &NUM1;
	NUM2 := &NUM2;
	SUM1 := NUM1 + NUM2;

	DBMS_OUTPUT.PUT_LINE('SUM OF NUM1 AND NUM2 IS : ' || SUM1);
END;
/