SET SERVEROUTPUT ON

DECLARE
	NUM1 NUMBER(3);
	NUM2 NUMBER(3);
	NUM3 NUMBER(3);

BEGIN
	NUM1 := &NUM1;
	NUM2 := &NUM2;
	NUM3 := &NUM3;

	IF NUM1 > NUM2 AND NUM1 > NUM3 THEN
		DBMS_OUTPUT.PUT_LINE('MAX NUM IS: ' || NUM1);

	ELSE
		IF NUM2 > NUM1 AND  NUM2 > NUM3 THEN
			DBMS_OUTPUT.PUT_LINE('MAX NUM IS: ' || NUM2);
		
		ELSE
			DBMS_OUTPUT.PUT_LINE('MAX NUM IS: '|| NUM3);
		END IF;
	END IF;
			
END;
/	
		