SET SERVEROUTPUT ON

DECLARE
	NUM1 NUMBER(3);
	RESULT NUMBER(3);
BEGIN
	NUM1 := &NUM1;

	RESULT := MOD(NUM1, 2);

	IF RESULT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NUMBER IS EVEN');
	ELSE
		DBMS_OUTPUT.PUT_LINE('NUMBER IS ODD');
	END IF;
END;
/