SET SERVEROUTPUT ON

DECLARE 
	vEMPNO NUMBER(5);
	vENAME VARCHAR(20);
	vSAL NUMBER(5,2);
BEGIN
	SELECT EMPNO, ENAME, SAL INTO vEMPNO, vENAME, vSAL FROM EMP WHERE EMPNO = &EMPNO;

	DBMS_OUTPUT.PUT_LINE(vEMPNO|| ' ' || vENAME|| ' ' || vSAL);
END;
/